//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassPhotoMVC4.Settings.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 262144.
        /// </summary>
        public static string maxuploadsize {
            get {
                return ResourceManager.GetString("maxuploadsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 280.
        /// </summary>
        public static string passheight {
            get {
                return ResourceManager.GetString("passheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220.
        /// </summary>
        public static string passwidth {
            get {
                return ResourceManager.GetString("passwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140.
        /// </summary>
        public static string previewheight {
            get {
                return ResourceManager.GetString("previewheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        public static string previewwidth {
            get {
                return ResourceManager.GetString("previewwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        public static string uploadheight {
            get {
                return ResourceManager.GetString("uploadheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string uploadpreviewh {
            get {
                return ResourceManager.GetString("uploadpreviewh", resourceCulture);
            }
        }
    }
}
